spring.application.name=ALERT-SERVICE
spring.datasource.url=jdbc:mysql://localhost:3306/alertdb
spring.datasource.username=root
spring.datasource.password=Aman
server.port=8081
#for hibernate connections
spring.jpa.hibernate.ddl-auto=update

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Enable registration with Eureka
#eureka.client.register-with-eureka=true
# Enable fetching the registry (optional for discovery)
#eureka.client.fetch-registry=true

# Kafka broker
spring.kafka.bootstrap-server=localhost:9092

# Consumer group & offset
spring.kafka.consumer.group-id=alertConsumer-Group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.max-poll-records=1


# Heartbeat/session settings
# 60 seconds session timeout
spring.kafka.consumer.properties.session.timeout.ms=60000

# 20 seconds heartbeat interval
spring.kafka.consumer.properties.heartbeat.interval.ms=20000

# 5 minutes max poll interval
spring.kafka.consumer.properties.max.poll.interval.ms=300000


# Avoid unnecessary errors when no messages
spring.kafka.consumer.properties.allow.auto.create.topics=true
spring.kafka.consumer.properties.fetch.min.bytes=1
spring.kafka.consumer.properties.fetch.max.wait.ms=500
spring.kafka.consumer.properties.retry.backoff.ms=1000

# Use ErrorHandlingDeserializer
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Delegate deserializers
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# JSON config
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=true

#to show sql queries on console in well format
#spring.jpa.show-sql=true
#spring.jpa.properties.format-sql=true



