spring.application.name=SERVICE-REGISTRY
server.port=8761


# disable Eureka client behavior
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Time in milliseconds
eureka.client.registry-fetch-interval-seconds=5
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.eureka-server-read-timeout-ms=10000


