spring.application.name=API-GATEWAY
server.port=9090

# Enable registration with Eureka
#eureka.client.register-with-eureka=true

# Enable fetching the registry (optional for discovery)
#eureka.client.fetch-registry=true

#routes configuration and it's url for route 0
#spring.cloud.gateway.routes[0].id=IDENTITY-SERVICE
#spring.cloud.gateway.routes[0].uri=lb://IDENTITY-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/userCredential/**
#Works only for String arguments or not Best Approach user .yml
#routes configuration and it's url for route 1
#spring.cloud.gateway.routes[1].id=ACCOUNTDETAIL-SERVICE
#spring.cloud.gateway.routes[1].uri=lb://ACCOUNTDETAIL-SERVICE
#spring.cloud.gateway.routes[1].predicates[0]=Path=/Account/**
#Filters -- comma separated list
#spring.cloud.gateway.routes[1].filters[0]=Authentication(requiredRoles=ROLE_USER,ROLE_ADMIN)











#spring.cloud.gateway.routes[0].filters[0].args.requiredRoles[0]=ROLE_USER
#spring.cloud.gateway.routes[0].filters[0].args.requiredRoles[1]=ROLE_ADMIN


